### PR TITLE
WIP: Remove role and permissions setting

### PR DESCRIPTION
**Pull request by rafaeldamasceno**
Hotfix for current deployments while awaiting for a final fix.

### CODE REVIEW

**Comment by rafaeldamasceno** [comment]
@StaticRocket Sorry to be bothering you like this, but would you happen to know why I get this error in the cache with these changes?

```
🦜 Elite Tauren Chieftain is connected!
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/handlers/serenity.rs:299:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: parrot::handlers::serenity::SerenityHandler::run_command::{{closure}}
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: tokio::runtime::task::core::CoreStage<T>::poll
   6: tokio::runtime::task::harness::poll_future
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::runtime::thread_pool::worker::Context::run_task
  10: tokio::runtime::thread_pool::worker::Context::run
  11: tokio::macros::scoped_tls::ScopedKey<T>::set
  12: tokio::runtime::thread_pool::worker::run
  13: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by StaticRocket** [comment]
They changed that function to no longer be asynchronous https://github.com/aquelemiguel/parrot/pull/197/files#diff-d7b79b6e237040d71edd73c66b5056f7ee28a8f66cdc4be5693cee8f9c3418a3L344-R341

**Comment by StaticRocket** [comment]
It's not a trivial update. My draft was almost done, though.

**Comment by rafaeldamasceno** [comment]
I haven't bumped Serenity, however. This was just an attempt at quickly fixing things while maintaining the same library versions, which sounds like it should work given that in guilds with the role set up the bot still works. But in this case, it's now returning `None`. Perhaps because no operation was done on the guild from permission/role stuff, it doesn't have it in cache? I just need to get the `guild.id` to fill in in https://github.com/rafaeldamasceno/parrot/blob/58e73368a31eb0bbbe738f2d3e8a563401a9dca5/src/handlers/serenity.rs#L305.

**Pull request closed without merging**
